import React, { useState, useEffect } from 'react';
import Modal from '../common/Modal';
import { Sparkles, RotateCcw } from 'lucide-react';

export default function TableFormModal({ isOpen, onClose, onSave, editingTable, autoGeneratedValues }) {
  const [formData, setFormData] = useState({
    table_number: '',
    table_name: '',
    floor: 'Main Dining',
    section: 'General',
    capacity: 4,
    table_type: 'STANDARD'
  });

  const [isAutoNumber, setIsAutoNumber] = useState(true);

  useEffect(() => {
    if (editingTable) {
      setFormData({
        table_number: editingTable.table_number || '',
        table_name: editingTable.table_name || '',
        floor: editingTable.floor || 'Main Dining',
        section: editingTable.section || 'General',
        capacity: editingTable.capacity || 4,
        table_type: editingTable.table_type || 'STANDARD'
      });
      setIsAutoNumber(false);
    } else {
      const defNum = autoGeneratedValues?.table_number || 'T01';
      const defName = autoGeneratedValues?.table_name || 'Table 1';
      setFormData({
        table_number: defNum,
        table_name: defName,
        floor: 'Main Dining',
        section: 'General',
        capacity: 4,
        table_type: 'STANDARD'
      });
      setIsAutoNumber(true);
    }
  }, [editingTable, autoGeneratedValues, isOpen]);

  const handleResetToAuto = () => {
    if (autoGeneratedValues) {
      setFormData(prev => ({
        ...prev,
        table_number: autoGeneratedValues.table_number,
        table_name: autoGeneratedValues.table_name
      }));
      setIsAutoNumber(true);
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    onSave(formData);
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={editingTable ? `Edit Table ${editingTable.table_number}` : 'Add New Restaurant Table'}
      maxWidth="max-w-lg"
    >
      <form onSubmit={handleSubmit} className="space-y-4">
        {!editingTable && (
          <div className="p-3 rounded-xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-between">
            <div className="flex items-center gap-2 text-xs text-amber-400 font-medium">
              <Sparkles className="w-4 h-4 shrink-0 animate-pulse" />
              <span>Table number & name auto-sequenced to next available slot.</span>
            </div>
            {!isAutoNumber && (
              <button
                type="button"
                onClick={handleResetToAuto}
                className="text-[11px] font-bold text-amber-400 hover:text-amber-300 flex items-center gap-1 underline"
              >
                <RotateCcw className="w-3 h-3" />
                <span>Reset to Auto</span>
              </button>
            )}
          </div>
        )}

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="block text-xs font-semibold text-slate-300">Table Number *</label>
              {!editingTable && isAutoNumber && (
                <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-400 bg-emerald-500/10 px-1.5 py-0.5 rounded border border-emerald-500/20">
                  Auto
                </span>
              )}
            </div>
            <input
              type="text"
              value={formData.table_number}
              onChange={(e) => {
                setFormData({ ...formData, table_number: e.target.value });
                setIsAutoNumber(false);
              }}
              required
              disabled={!!editingTable}
              placeholder="e.g. T06"
              className="w-full px-3.5 py-2.5 rounded-xl bg-slate-800 border border-slate-700 text-white focus:outline-none focus:border-amber-500 disabled:opacity-50 text-sm font-mono font-semibold"
            />
          </div>
          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="block text-xs font-semibold text-slate-300">Table Name *</label>
              {!editingTable && isAutoNumber && (
                <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-400 bg-emerald-500/10 px-1.5 py-0.5 rounded border border-emerald-500/20">
                  Auto
                </span>
              )}
            </div>
            <input
              type="text"
              value={formData.table_name}
              onChange={(e) => {
                setFormData({ ...formData, table_name: e.target.value });
                setIsAutoNumber(false);
              }}
              required
              placeholder="e.g. Table 6"
              className="w-full px-3.5 py-2.5 rounded-xl bg-slate-800 border border-slate-700 text-white focus:outline-none focus:border-amber-500 text-sm font-semibold"
            />
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1">Floor</label>
            <input
              type="text"
              value={formData.floor}
              onChange={(e) => setFormData({ ...formData, floor: e.target.value })}
              placeholder="e.g. Main Dining"
              className="w-full px-3.5 py-2.5 rounded-xl bg-slate-800 border border-slate-700 text-white focus:outline-none focus:border-amber-500 text-sm"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1">Section / Area</label>
            <input
              type="text"
              value={formData.section}
              onChange={(e) => setFormData({ ...formData, section: e.target.value })}
              placeholder="e.g. Section B"
              className="w-full px-3.5 py-2.5 rounded-xl bg-slate-800 border border-slate-700 text-white focus:outline-none focus:border-amber-500 text-sm"
            />
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1">Seating Capacity</label>
            <input
              type="number"
              min="1"
              max="50"
              value={formData.capacity}
              onChange={(e) => setFormData({ ...formData, capacity: parseInt(e.target.value) || 1 })}
              required
              className="w-full px-3.5 py-2.5 rounded-xl bg-slate-800 border border-slate-700 text-white focus:outline-none focus:border-amber-500 text-sm font-bold"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1">Table Type</label>
            <select
              value={formData.table_type}
              onChange={(e) => setFormData({ ...formData, table_type: e.target.value })}
              className="w-full px-3.5 py-2.5 rounded-xl bg-slate-800 border border-slate-700 text-white focus:outline-none focus:border-amber-500 text-sm font-medium"
            >
              <option value="STANDARD">STANDARD</option>
              <option value="BOOTH">BOOTH</option>
              <option value="VIP">VIP</option>
              <option value="OUTDOOR">OUTDOOR</option>
            </select>
          </div>
        </div>

        <div className="mt-6 flex justify-end gap-3 pt-4 border-t border-slate-800">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2.5 rounded-xl bg-slate-800 text-slate-300 hover:bg-slate-700 text-sm font-medium transition-colors"
          >
            Cancel
          </button>
          <button
            type="submit"
            className="px-6 py-2.5 rounded-xl bg-amber-500 text-slate-950 font-bold hover:bg-amber-400 text-sm transition-colors shadow-lg shadow-amber-500/20"
          >
            {editingTable ? 'Save Changes' : 'Create Table'}
          </button>
        </div>
      </form>
    </Modal>
  );
}

