import React, { useState, useEffect, useCallback } from 'react';
import { useSearchParams } from 'react-router-dom';
import api from '../../../services/api';
import { useAuth } from '../../../context/AuthContext';
import TableCard from '../../../components/tables/TableCard';
import TableFormModal from '../../../components/tables/TableFormModal';
import QRPrintModal from '../../../components/tables/QRPrintModal';
import { Plus, Search, Filter, RefreshCw, Grid2X2, X } from 'lucide-react';

// Helper function to calculate next available table number and name locally from list (gap-filling)
export function getNextTableNumberLocally(tablesList = []) {
  const usedNumbers = new Set();
  for (const t of tablesList) {
    const matchNum = String(t.table_number || '').match(/\d+/);
    if (matchNum) {
      const n = parseInt(matchNum[0], 10);
      if (!isNaN(n) && n > 0) usedNumbers.add(n);
    }
    const matchName = String(t.table_name || '').match(/\d+/);
    if (matchName) {
      const n = parseInt(matchName[0], 10);
      if (!isNaN(n) && n > 0) usedNumbers.add(n);
    }
  }

  let nextNum = 1;
  while (usedNumbers.has(nextNum)) {
    nextNum++;
  }

  const table_number = nextNum < 10 ? `T0${nextNum}` : `T${nextNum}`;
  const table_name = `Table ${nextNum}`;
  return { number: nextNum, table_number, table_name };
}

export default function TableManagementPage() {
  const { user } = useAuth();
  const [searchParams, setSearchParams] = useSearchParams();
  const isAdminOrManager = ['ADMIN', 'MANAGER', 'RESTAURANT_ADMIN', 'SUPER_ADMIN'].includes(user?.role);
  
  const [tables, setTables] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [selectedFloor, setSelectedFloor] = useState('');
  const [selectedStatus, setSelectedStatus] = useState(searchParams.get('status') || '');

  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingTable, setEditingTable] = useState(null);
  const [autoGeneratedValues, setAutoGeneratedValues] = useState({ table_number: 'T01', table_name: 'Table 1' });

  const [isQROpen, setIsQROpen] = useState(false);
  const [selectedQRTable, setSelectedQRTable] = useState(null);

  // Sync state when URL search params change (e.g. clicked from Live Operations)
  useEffect(() => {
    const urlStatus = searchParams.get('status') || '';
    setSelectedStatus(urlStatus);
  }, [searchParams]);

  const handleStatusFilterChange = (statusValue) => {
    setSelectedStatus(statusValue);
    const newParams = new URLSearchParams(searchParams);
    if (statusValue) {
      newParams.set('status', statusValue);
    } else {
      newParams.delete('status');
    }
    setSearchParams(newParams);
  };

  const fetchTables = useCallback(async () => {
    setLoading(true);
    try {
      const params = {};
      if (search) params.search = search;
      if (selectedFloor) params.floor = selectedFloor;
      if (selectedStatus) params.status = selectedStatus;

      const res = await api.get('/tables', { params });
      if (res.success) {
        setTables(res.data);
      }
    } catch (err) {
      console.error('Failed to fetch tables:', err);
    } finally {
      setLoading(false);
    }
  }, [search, selectedFloor, selectedStatus]);

  useEffect(() => {
    fetchTables();
  }, [fetchTables]);

  const handleOpenAddModal = async () => {
    setEditingTable(null);
    try {
      const res = await api.get('/tables/next-number');
      if (res.success && res.data) {
        setAutoGeneratedValues(res.data);
      } else {
        setAutoGeneratedValues(getNextTableNumberLocally(tables));
      }
    } catch {
      setAutoGeneratedValues(getNextTableNumberLocally(tables));
    }
    setIsFormOpen(true);
  };

  const handleSaveTable = async (formData) => {
    try {
      if (editingTable) {
        await api.put(`/tables/${editingTable.id}`, formData);
      } else {
        await api.post('/tables', formData);
      }
      setIsFormOpen(false);
      setEditingTable(null);
      fetchTables();
    } catch (err) {
      alert(err.message || 'Failed to save table');
    }
  };

  const handleDeleteTable = async (table) => {
    if (window.confirm(`Are you sure you want to delete ${table.table_name} (${table.table_number})? This action will free up the table number for future auto-generation.`)) {
      try {
        await api.delete(`/tables/${table.id}`);
        fetchTables();
      } catch (err) {
        alert(err.message || 'Failed to delete table');
      }
    }
  };

  const handleStatusChange = async (tableId, newStatus) => {
    try {
      await api.patch(`/tables/${tableId}/status`, { status: newStatus });
      fetchTables();
    } catch (err) {
      alert(err.message || 'Failed to update table status');
    }
  };

  const handleRegenerateQR = async (table) => {
    if (window.confirm(`Are you sure you want to regenerate the QR code for Table ${table.table_number}? The old QR code will stop working.`)) {
      try {
        await api.post(`/tables/${table.id}/qr/regenerate`);
        fetchTables();
      } catch (err) {
        alert(err.message || 'Failed to regenerate QR code');
      }
    }
  };

  // Get unique floor options
  const floors = Array.from(new Set(tables.map(t => t.floor))).filter(Boolean);

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-white tracking-wide flex items-center gap-2">
            <Grid2X2 className="w-7 h-7 text-amber-500" />
            <span>Table Management</span>
          </h2>
          <p className="text-slate-400 text-sm">
            Manage restaurant tables, floor layouts, statuses, and unique QR tokens with smart auto-sequenced numbering
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={fetchTables}
            className="p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-slate-400 hover:text-white transition-colors"
            title="Refresh Table List"
          >
            <RefreshCw className="w-5 h-5" />
          </button>
          {isAdminOrManager && (
            <button
              onClick={handleOpenAddModal}
              className="py-2.5 px-4 rounded-xl bg-amber-500 text-slate-950 font-bold hover:bg-amber-400 flex items-center gap-2 shadow-lg shadow-amber-500/20 transition-all text-sm"
            >
              <Plus className="w-5 h-5" />
              <span>Add Table</span>
            </button>
          )}
        </div>
      </div>

      {/* Filter Bar */}
      <div className="glass-panel bg-slate-900/60 border border-slate-800 rounded-2xl p-4 flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="relative w-full md:w-80">
          <Search className="w-5 h-5 absolute left-3.5 top-3 text-slate-500" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search table number or name..."
            className="w-full pl-11 pr-4 py-2.5 rounded-xl bg-slate-800/80 border border-slate-700 text-white placeholder-slate-500 text-sm focus:outline-none focus:border-amber-500"
          />
        </div>

        <div className="flex flex-wrap items-center gap-3 w-full md:w-auto justify-end">
          {selectedStatus && (
            <div className="flex items-center gap-2 text-xs bg-amber-500/10 border border-amber-500/30 text-amber-400 px-3 py-1.5 rounded-xl font-bold">
              <span>Filtered: <strong>{selectedStatus.replace('_', ' ')}</strong></span>
              <button
                onClick={() => handleStatusFilterChange('')}
                className="p-0.5 hover:bg-amber-500/20 text-amber-300 rounded-full transition"
                title="Clear Status Filter"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            </div>
          )}

          <div className="flex items-center gap-3">
            <Filter className="w-4 h-4 text-slate-500 shrink-0" />
            
            <select
              value={selectedFloor}
              onChange={(e) => setSelectedFloor(e.target.value)}
              className="px-3 py-2 rounded-xl bg-slate-800 border border-slate-700 text-slate-200 text-xs font-medium focus:outline-none focus:border-amber-500"
            >
              <option value="">All Floors</option>
              {floors.map(f => <option key={f} value={f}>{f}</option>)}
            </select>

            <select
              value={selectedStatus}
              onChange={(e) => handleStatusFilterChange(e.target.value)}
              className="px-3 py-2 rounded-xl bg-slate-800 border border-slate-700 text-slate-200 text-xs font-medium focus:outline-none focus:border-amber-500 font-semibold"
            >
              <option value="">All Statuses</option>
              <option value="AVAILABLE">AVAILABLE</option>
              <option value="OCCUPIED">OCCUPIED</option>
              <option value="ORDERING">ORDERING</option>
              <option value="ATTENTION">ATTENTION NEEDED</option>
              <option value="RESERVED">RESERVED</option>
              <option value="BILL_REQUESTED">BILL REQUESTED</option>
              <option value="BILL_PAID">BILL PAID</option>
              <option value="CLEANING">CLEANING</option>
              <option value="OUT_OF_SERVICE">OUT OF SERVICE</option>
            </select>
          </div>
        </div>
      </div>

      {/* Tables Grid */}
      {loading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 2xl:grid-cols-4 gap-5">
          {[1, 2, 3, 4].map(i => (
            <div key={i} className="h-56 rounded-2xl bg-slate-900/50 border border-slate-800 animate-pulse"></div>
          ))}
        </div>
      ) : tables.length === 0 ? (
        <div className="glass-panel bg-slate-900/40 border border-slate-800 rounded-2xl p-12 text-center text-slate-400">
          <Grid2X2 className="w-12 h-12 text-slate-600 mx-auto mb-3" />
          <h3 className="text-lg font-semibold text-slate-300">No {selectedStatus ? selectedStatus.replace('_', ' ') : ''} Tables Found</h3>
          <p className="text-sm text-slate-500 mt-1">
            {selectedStatus ? (
              <button
                onClick={() => handleStatusFilterChange('')}
                className="text-amber-400 underline font-semibold mt-1"
              >
                Clear status filter to view all tables
              </button>
            ) : (
              'Try adjusting search filters or add a new table.'
            )}
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 2xl:grid-cols-4 gap-5">
          {tables.map(table => (
            <TableCard
              key={table.id}
              table={table}
              onEdit={(t) => {
                setEditingTable(t);
                setIsFormOpen(true);
              }}
              onDelete={handleDeleteTable}
              onStatusChange={handleStatusChange}
              onQRAction={(t) => {
                setSelectedQRTable(t);
                setIsQROpen(true);
              }}
              onRegenerateQR={handleRegenerateQR}
            />
          ))}
        </div>
      )}

      {/* Form Modal */}
      <TableFormModal
        isOpen={isFormOpen}
        onClose={() => setIsFormOpen(false)}
        onSave={handleSaveTable}
        editingTable={editingTable}
        autoGeneratedValues={autoGeneratedValues}
      />

      {/* QR Modal */}
      <QRPrintModal
        isOpen={isQROpen}
        onClose={() => setIsQROpen(false)}
        table={selectedQRTable}
      />
    </div>
  );
}

