import React, { useState, useEffect, useCallback } from 'react';
import { useSearchParams } from 'react-router-dom';
import api from '../../../services/api';
import { useAuth } from '../../../context/AuthContext';
import TableCard from '../../../components/tables/TableCard';
import TableFormModal from '../../../components/tables/TableFormModal';
import QRPrintModal from '../../../components/tables/QRPrintModal';
import { Plus, Search, Filter, RefreshCw, Grid2X2, X } from 'lucide-react';

// Helper function to calculate next available table number and name locally from list (gap-filling)
export function getNextTableNumberLocally(tablesList = []) {
  const usedNumbers = new Set();
  for (const t of tablesList) {
    const matchNum = String(t.table_number || '').match(/\d+/);
    if (matchNum) {
      const n = parseInt(matchNum[0], 10);
      if (!isNaN(n) && n > 0) usedNumbers.add(n);
    }
    const matchName = String(t.table_name || '').match(/\d+/);
    if (matchName) {
      const n = parseInt(matchName[0], 10);
      if (!isNaN(n) && n > 0) usedNumbers.add(n);
    }
  }

  let nextNum = 1;
  while (usedNumbers.has(nextNum)) {
    nextNum++;
  }

  const table_number = nextNum < 10 ? `T0${nextNum}` : `T${nextNum}`;
  const table_name = `Table ${nextNum}`;
  return { number: nextNum, table_number, table_name };
}

export default function TableManagementPage() {
  const { user } = useAuth();
  const [searchParams, setSearchParams] = useSearchParams();
  const isAdminOrManager = ['ADMIN', 'MANAGER', 'RESTAURANT_ADMIN', 'SUPER_ADMIN'].includes(user?.role);
  
  const [tables, setTables] = useState([]);
  const [allTables, setAllTables] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [selectedFloor, setSelectedFloor] = useState('');
  const [selectedStatus, setSelectedStatus] = useState(searchParams.get('status') || '');

  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingTable, setEditingTable] = useState(null);
  const [autoGeneratedValues, setAutoGeneratedValues] = useState({ table_number: 'T01', table_name: 'Table 1' });

  const [isQROpen, setIsQROpen] = useState(false);
  const [selectedQRTable, setSelectedQRTable] = useState(null);

  // Sync state when URL search params change (e.g. clicked from Live Operations)
  useEffect(() => {
    const urlStatus = searchParams.get('status') || '';
    setSelectedStatus(urlStatus);
  }, [searchParams]);

  const handleStatusFilterChange = (statusValue) => {
    setSelectedStatus(statusValue);
    const newParams = new URLSearchParams(searchParams);
    if (statusValue) {
      newParams.set('status', statusValue);
    } else {
      newParams.delete('status');
    }
    setSearchParams(newParams);
  };

  const handleClearAllFilters = () => {
    setSearch('');
    setSelectedFloor('');
    setSelectedStatus('');
    setSearchParams({});
  };

  const fetchTables = useCallback(async () => {
    setLoading(true);
    try {
      const params = {};
      if (search) params.search = search;
      if (selectedFloor) params.floor = selectedFloor;
      if (selectedStatus) params.status = selectedStatus;

      // Always fetch full table list for gap filling reference
      const [filteredRes, allRes] = await Promise.all([
        api.get('/tables', { params }),
        api.get('/tables').catch(() => ({ success: false, data: [] }))
      ]);

      if (filteredRes.success) {
        setTables(filteredRes.data);
      }
      if (allRes.success) {
        setAllTables(allRes.data);
      } else if (filteredRes.success && (!search && !selectedFloor && !selectedStatus)) {
        setAllTables(filteredRes.data);
      }
    } catch (err) {
      console.error('Failed to fetch tables:', err);
    } finally {
      setLoading(false);
    }
  }, [search, selectedFloor, selectedStatus]);

  useEffect(() => {
    fetchTables();
  }, [fetchTables]);

  const handleOpenAddModal = async () => {
    setEditingTable(null);
    try {
      const res = await api.get('/tables/next-number');
      const tableData = res?.data || res;
      if (tableData && tableData.table_number) {
        setAutoGeneratedValues(tableData);
      } else {
        const poolToUse = allTables.length > 0 ? allTables : tables;
        setAutoGeneratedValues(getNextTableNumberLocally(poolToUse));
      }
    } catch (err) {
      console.error('Failed to fetch next table number:', err);
      const poolToUse = allTables.length > 0 ? allTables : tables;
      setAutoGeneratedValues(getNextTableNumberLocally(poolToUse));
    }
    setIsFormOpen(true);
  };

  const handleSaveTable = async (formData) => {
    if (editingTable) {
      await api.put(`/tables/${editingTable.id}`, formData);
    } else {
      await api.post('/tables', formData);
    }
    setIsFormOpen(false);
    setEditingTable(null);
    fetchTables();
  };

  const handleDeleteTable = async (table) => {
    if (window.confirm(`Are you sure you want to delete ${table.table_name} (${table.table_number})? This action will free up the table number for future auto-generation.`)) {
      try {
        await api.delete(`/tables/${table.id}`);
        fetchTables();
      } catch (err) {
        alert(err.message || 'Failed to delete table');
      }
    }
  };

  const handleStatusChange = async (tableId, newStatus) => {
    try {
      await api.patch(`/tables/${tableId}/status`, { status: newStatus });
      fetchTables();
    } catch (err) {
      alert(err.message || 'Failed to update table status');
    }
  };

  const handleRegenerateQR = async (table) => {
    if (window.confirm(`Are you sure you want to regenerate the QR code for Table ${table.table_number}? The old QR code will stop working.`)) {
      try {
        await api.post(`/tables/${table.id}/qr/regenerate`);
        fetchTables();
      } catch (err) {
        alert(err.message || 'Failed to regenerate QR code');
      }
    }
  };

  // Get unique floor options from all tables
  const floors = Array.from(new Set((allTables.length > 0 ? allTables : tables).map(t => t.floor))).filter(Boolean);

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="bg-white border border-blue-100 rounded-2xl p-4 sm:p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 shadow-sm">
        <div>
          <h2 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight flex items-center gap-2">
            <Grid2X2 className="w-6 h-6 text-amber-600" />
            <span>Table Management</span>
          </h2>
          <p className="text-slate-600 text-xs sm:text-sm mt-0.5">
            Manage restaurant tables, floor layouts, statuses, and unique QR tokens with smart auto-sequenced numbering
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={fetchTables}
            className="p-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 border border-slate-300 text-slate-700 hover:text-black transition-colors"
            title="Refresh Table List"
          >
            <RefreshCw className="w-4 h-4" />
          </button>
          {isAdminOrManager && (
            <button
              onClick={handleOpenAddModal}
              className="py-2.5 px-4 rounded-xl bg-amber-500 text-slate-950 font-black hover:bg-amber-400 flex items-center gap-2 shadow-sm transition-all text-xs uppercase tracking-wider"
            >
              <Plus className="w-4 h-4 stroke-[3]" />
              <span>Add Table</span>
            </button>
          )}
        </div>
      </div>

      {/* Filter Bar */}
      <div className="bg-white border border-blue-100 rounded-2xl p-3 sm:p-4 flex flex-col md:flex-row items-center justify-between gap-4 shadow-sm">
        <div className="relative w-full md:w-80">
          <Search className="w-4 h-4 absolute left-3.5 top-3 text-slate-400" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search table number or name..."
            className="w-full pl-10 pr-4 py-2 rounded-xl bg-slate-50 border border-slate-200 text-slate-900 placeholder-slate-400 text-xs font-semibold focus:outline-none focus:border-amber-500"
          />
        </div>

        <div className="flex flex-wrap items-center gap-3 w-full md:w-auto justify-end">
          {(selectedStatus || selectedFloor || search) && (
            <div className="flex items-center gap-2 text-xs bg-amber-50 border border-amber-300 text-amber-900 px-3 py-1.5 rounded-xl font-bold">
              <span>Showing {tables.length} of {allTables.length} tables</span>
              <button
                onClick={handleClearAllFilters}
                className="p-0.5 hover:bg-amber-200 text-amber-950 rounded-full transition ml-1"
                title="Clear All Filters"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            </div>
          )}

          <div className="flex items-center gap-2.5">
            <Filter className="w-4 h-4 text-slate-400 shrink-0" />
            
            <select
              value={selectedFloor}
              onChange={(e) => setSelectedFloor(e.target.value)}
              className="px-3 py-1.5 rounded-xl bg-slate-50 border border-slate-200 text-slate-800 text-xs font-bold focus:outline-none focus:border-amber-500"
            >
              <option value="">All Floors</option>
              {floors.map(f => <option key={f} value={f}>{f}</option>)}
            </select>

            <select
              value={selectedStatus}
              onChange={(e) => handleStatusFilterChange(e.target.value)}
              className="px-3 py-1.5 rounded-xl bg-slate-50 border border-slate-200 text-slate-800 text-xs font-bold focus:outline-none focus:border-amber-500"
            >
              <option value="">All Statuses</option>
              <option value="AVAILABLE">AVAILABLE</option>
              <option value="OCCUPIED">OCCUPIED</option>
              <option value="ORDERING">ORDERING</option>
              <option value="ATTENTION">ATTENTION NEEDED</option>
              <option value="RESERVED">RESERVED</option>
              <option value="BILL_REQUESTED">BILL REQUESTED</option>
              <option value="BILL_PAID">BILL PAID</option>
              <option value="CLEANING">CLEANING</option>
              <option value="OUT_OF_SERVICE">OUT OF SERVICE</option>
            </select>
          </div>
        </div>
      </div>

      {/* Tables Grid */}
      {loading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 2xl:grid-cols-4 gap-5">
          {[1, 2, 3, 4].map(i => (
            <div key={i} className="h-56 rounded-2xl bg-white border border-blue-100 animate-pulse shadow-sm"></div>
          ))}
        </div>
      ) : tables.length === 0 ? (
        <div className="bg-white border border-amber-200 rounded-2xl p-10 text-center text-slate-600 shadow-sm space-y-3">
          <div className="w-14 h-14 rounded-full bg-amber-100 text-amber-700 flex items-center justify-center mx-auto">
            <Grid2X2 className="w-7 h-7 text-amber-700" />
          </div>
          <div>
            <h3 className="text-lg font-black text-slate-900">
              {selectedStatus || selectedFloor || search ? 'No Matching Tables Found' : 'No Restaurant Tables Created Yet'}
            </h3>
            <p className="text-xs text-slate-600 max-w-md mx-auto mt-1 font-medium">
              {allTables.length > 0 ? (
                <>
                  You have <strong className="text-slate-900">{allTables.length} total table(s)</strong> in your restaurant, but none match the current filter selection
                  {selectedStatus && <span> (Status: <strong>{selectedStatus.replace('_', ' ')}</strong>)</span>}.
                </>
              ) : (
                'Get started by adding your first restaurant table using smart auto-sequenced numbering.'
              )}
            </p>
          </div>
          {(selectedStatus || selectedFloor || search) ? (
            <div className="pt-2">
              <button
                onClick={handleClearAllFilters}
                className="px-5 py-2.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-black text-xs uppercase tracking-wider shadow-xs transition"
              >
                Clear All Filters & View All {allTables.length} Tables
              </button>
            </div>
          ) : (
            isAdminOrManager && (
              <div className="pt-2">
                <button
                  onClick={handleOpenAddModal}
                  className="px-5 py-2.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-black text-xs uppercase tracking-wider shadow-xs transition"
                >
                  Add Your First Table
                </button>
              </div>
            )
          )}
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 2xl:grid-cols-4 gap-5">
          {tables.map(table => (
            <TableCard
              key={table.id}
              table={table}
              onEdit={(t) => {
                setEditingTable(t);
                setIsFormOpen(true);
              }}
              onDelete={handleDeleteTable}
              onStatusChange={handleStatusChange}
              onQRAction={(t) => {
                setSelectedQRTable(t);
                setIsQROpen(true);
              }}
              onRegenerateQR={handleRegenerateQR}
            />
          ))}
        </div>
      )}

      {/* Form Modal */}
      <TableFormModal
        isOpen={isFormOpen}
        onClose={() => setIsFormOpen(false)}
        onSave={handleSaveTable}
        editingTable={editingTable}
        autoGeneratedValues={autoGeneratedValues}
      />

      {/* QR Modal */}
      <QRPrintModal
        isOpen={isQROpen}
        onClose={() => setIsQROpen(false)}
        table={selectedQRTable}
      />
    </div>
  );
}

